/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-base': '#F5F2EE',
        'bg-base-dark': '#1C1A18',
        'bg-surface': '#FAF8F5',
        'bg-surface-dark': '#242220',
        'bg-elevated': '#FFFFFF',
        'bg-elevated-dark': '#2C2A28',
        'bg-sidebar': 'rgba(245, 242, 238, 0.72)',
        'bg-sidebar-dark': 'rgba(28, 26, 24, 0.78)',
        'bg-sidebar-active': 'rgba(230, 226, 220, 0.85)',
        'bg-sidebar-active-dark': 'rgba(60, 58, 56, 0.85)',
        'border-primary': 'rgba(0, 0, 0, 0.06)',
        'border-primary-dark': 'rgba(255, 255, 255, 0.08)',
        'border-secondary': 'rgba(0, 0, 0, 0.04)',
        'border-secondary-dark': 'rgba(255, 255, 255, 0.05)',
        'border-focus': 'rgba(0, 0, 0, 0.15)',
        'border-focus-dark': 'rgba(255, 255, 255, 0.2)',
        'text-primary': '#1A1814',
        'text-primary-dark': '#F0EDE8',
        'text-secondary': '#6B6560',
        'text-secondary-dark': '#9A9590',
        'text-tertiary': '#A39E98',
        'text-tertiary-dark': '#6B6560',
        'text-inverse': '#FFFFFF',
        'accent-primary': '#4A7C6F',
        'accent-primary-dark': '#5FA08F',
        'accent-primary-hover': '#3D6A5E',
        'accent-primary-hover-dark': '#7BB8A8',
        'accent-primary-muted': 'rgba(74, 124, 111, 0.12)',
        'accent-primary-muted-dark': 'rgba(95, 160, 143, 0.15)',
        'accent-secondary': '#8B7355',
        'accent-cyan': '#3A8B8C',
        'status-success': '#4A7C6F',
        'status-warning': '#B8923A',
        'status-error': '#B85C50',
        'status-info': '#5A7D9A',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'titlebar': '38px',
        'statusbar': '28px',
      },
      borderRadius: {
        'radius-sm': '6px',
        'radius-md': '8px',
        'radius-lg': '12px',
        'radius-xl': '16px',
        'radius-full': '9999px',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      fontFamily: {
        'inter': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', '"SF Mono"', '"Fira Code"', 'monospace'],
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'card': '0 24px 64px rgba(0, 0, 0, 0.08), 0 8px 24px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 32px 72px rgba(0, 0, 0, 0.12), 0 12px 32px rgba(0, 0, 0, 0.06)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.08), 0 2px 8px rgba(0, 0, 0, 0.04)',
        'login-btn': '0 4px 12px rgba(74, 124, 111, 0.3)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "0.7" },
        },
        "spin": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "float": "float 4s ease-in-out infinite",
        "glow-pulse": "glow-pulse 6s ease-in-out infinite",
        "spin": "spin 1s linear infinite",
        "blink": "blink 1s step-end infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
